class Translator {

  static const Map<String, Map<String, String>> _data = {
    'it': {
      'system_language': 'Sistema',
      'app_title': 'PickUp',
      'search_here': 'Cerca in questa zona',
      'language': 'Lingua',
      'settings': 'Impostazioni',
      'dark_mode': 'Modalità Scura',
      'search_radius': 'Raggio di ricerca',
      'navigator': 'Navigatore',
      'units': 'Unità di misura',
      'clear_cache': 'Svuota cache mappa',
      'cache_cleared': 'Cache svuotata!',
      'developed_by': 'Sviluppato da',
      'address': 'Indirizzo',
      'surface': 'Superficie',
      'take_me_here': 'Portami qui',
      'not_specified': 'Non specificata',
      'unknown': 'Sconosciuto',
      'basketball': 'Basket',
      'soccer': 'Calcio',
      'tennis': 'Tennis',
      'volleyball': 'Pallavolo',
      'volley': 'Pallavolo',
      'beachvolleyball': 'Beach Volley',
      'open_menu': 'Apri menu',
      'all_sports': 'Tutti gli sport',
      'select_all': 'Seleziona tutto',
      'deselect_all': 'Deseleziona tutto',
      'phone': 'Telefono',
      'website': 'Sito web',
      'sports': 'Sport',
      'fitness': 'Fitness',
      'climbing': 'Arrampicata',
      'swimming': 'Nuoto',
      'yoga': 'Yoga',
      'gymnastics': 'Ginnastica',
      'cycling': 'Ciclismo',
      'running': 'Corsa',
      'table_tennis': 'Tennis da tavolo',
      'skiing': 'Sci',
      'padel': 'Padel',
      'gym': 'Palestra',
      'football': 'Calcio',
      'snowboarding': 'Snowboard',
      'rugby_union': 'Rugby',
      'rugby_league': 'Rugby',
      'rugby': 'Rugby',
      'american_football': 'Football Americano',
      'baseball': 'Baseball',
      'softball': 'Softball',
      'skateboard': 'Skateboard',
      'skateboarding': 'Skateboard',
      'golf': 'Golf',
      'martial_arts': 'Arti Marziali',
      'karate': 'Karate',
      'judo': 'Judo',
      'equestrian': 'Equitazione',
      'horse_riding': 'Equitazione',
      'hockey': 'Hockey',
      'ice_hockey': 'Hockey su ghiaccio',
      'boules': 'Bocce',
      'bocce': 'Bocce',
      'address_not_available': 'Indirizzo non disponibile',
      'boxing': 'Boxe',
      'calisthenics': 'Calisthenics',
      'snowboard': 'Snowboard',
      'roller_hockey': 'Hockey su rotelle',
      'theme_system': 'Automatico',
      'theme_light': 'Chiaro',
      'theme_dark': 'Scuro',
      'theme' : 'Tema',
      'see_results': 'Vedi risultati'
    },
    'en': {
      'system_language': 'System',
      'app_title': 'PickUp',
      'search_here': 'Search in this area',
      'language': 'Language',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'search_radius': 'Search radius',
      'navigator': 'Navigator',
      'units': 'Units',
      'clear_cache': 'Clear map cache',
      'cache_cleared': 'Cache cleared!',
      'developed_by': 'Developed by',
      'address': 'Address',
      'surface': 'Surface',
      'take_me_here': 'Take me here',
      'not_specified': 'Not specified',
      'unknown': 'Unknown',
      'basketball': 'Basketball',
      'soccer': 'Soccer',
      'tennis': 'Tennis',
      'volleyball': 'Volleyball',
      'volley': 'Volleyball',
      'beachvolleyball': 'Beach Volley',
      'open_menu': 'Open menu',
      'all_sports': 'All sports',
      'select_all': 'Select all',
      'deselect_all': 'Deselect all',
      'phone': 'Phone',
      'website': 'Website',
      'sports': 'Sports',
      'fitness': 'Fitness',
      'climbing': 'Climbing',
      'swimming': 'Swimming',
      'yoga': 'Yoga',
      'gymnastics': 'Gymnastics',
      'cycling': 'Cycling',
      'running': 'Running',
      'table_tennis': 'Table Tennis',
      'skiing': 'Skiing',
      'padel': 'Padel',
      'gym': 'Gym',
      'football': 'Football',
      'snowboarding': 'Snowboard',
      'rugby_union': 'Rugby',
      'rugby_league': 'Rugby',
      'rugby': 'Rugby',
      'american_football': 'American Football',
      'baseball': 'Baseball',
      'softball': 'Softball',
      'skateboard': 'Skateboard',
      'skateboarding': 'Skateboard',
      'golf': 'Golf',
      'martial_arts': 'Martial Arts',
      'karate': 'Karate',
      'judo': 'Judo',
      'equestrian': 'Equestrian',
      'horse_riding': 'Equestrian',
      'hockey': 'Hockey',
      'ice_hockey': 'Ice Hockey',
      'boules': 'Boules',
      'bocce': 'Boules',
      'address_not_available': 'Address not available',
      'boxing': 'Boxing',
      'calisthenics': 'Calisthenics',
      'snowboard': 'Snowboard',
      'roller_hockey': 'Roller Hockey',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme' : 'Theme',
      'see_results': 'See results'
    }
  };

  static String of(String key, {String? overrideLang}) {
    // 1. Se forziamo una lingua (es. durante il caricamento), usa quella
    // 2. Altrimenti usa currentLanguage (che aggiorneremo dal MaterialApp)
    // 3. Fallback su 'it'
    String lang = overrideLang ?? currentLanguage;
    
    return _data[lang]?[key.toLowerCase()] ?? 
           _data['it']?[key.toLowerCase()] ?? // Fallback su italiano se manca in EN
           key;
  }

  static String currentLanguage = 'it';
}